# FixField for vFFA

In [1]:
from extract_ff import co_transfermatrix, extract_da, run_fixfield, run_fixfield_da

import decoupling_matrix as dm

import numpy as np

0.11059638588513682 0.11044803618570827


In [2]:
b0f, b0d, m, xs, tilt_deg = -1., 1.15, 1.31, 0, 0

# PART A: closed orbit

## 1. compute closed orbit and transfer matrix with `FixField`

In [3]:
output_fn = 'output.txt'

can take ~1min:

In [4]:
run_fixfield(output_fn, b0f, b0d, m, xs, tilt_deg)

*** Running fixfield.exe...
*** Finished running fixfield.exe, output file written!


In [5]:
#!cat output.txt

In [6]:
(x_clo, xprime_clo, z_clo, zprime_clo), transfer_matrix = co_transfermatrix(output_fn)

(x_clo, xprime_clo, z_clo, zprime_clo), transfer_matrix

((4.359510989, 2.9023431458e-10, -0.7286268675, -3.2797377139e-10),
 array([[-0.011996, -0.911259,  0.138038,  0.211074],
        [ 1.106516, -0.011575, -0.146542, -0.28276 ],
        [-0.285788,  0.209392,  0.782058,  3.079843],
        [-0.146732,  0.13847 , -0.128942,  0.781688]]))

## 2. compute tunes and decoupling matrix

In [7]:
dm.get_tunes(transfer_matrix)

(0.24342766667449875, 0.12003865039207802)

In [8]:
r, r_inv, t = dm.decoupling_matrix(transfer_matrix)

r, r_inv, t

norm<0
j= 0
beta: 0.951565596037006
tune:  -0.24342766667449875 1-tune 0.7565723333255012
j= 2
beta: 4.381150016265674
tune:  0.12003865039207802 1-tune 0.8799613496079219
[[ 1.02513399e+00+8.49566505e-17j  2.50827431e-05-9.75482237e-01j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
 [-1.02513399e+00+8.49566505e-17j -2.50827431e-05-9.75482237e-01j
   0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
  -6.80630538e-06+4.77755767e-01j  2.09311969e+00+2.56333232e-16j]
 [ 0.00000000e+00+0.00000000e+00j  0.00000000e+00+0.00000000e+00j
   6.80630538e-06+4.77755767e-01j -2.09311969e+00+2.56333232e-16j]]
before final norm
[[ 1.42980351e-21-2.07631135e+00j  4.95509685e-17-1.63728081e-16j
  -6.43461502e-23-3.86730236e-01j  5.40148114e-17+3.10103969e-05j]
 [-8.42723178e-17+1.80830005e-16j -1.31694852e-21-2.07631135e+00j
  -4.53413572e-18+3.81616394e-05j -5.40199481e-21+7.92425008e-01j]
 [-6.366292

(array([[ 1.03815567e+00+7.14901753e-22j,  8.18640403e-17+2.47754843e-17j,
          1.93365118e-01-3.21730751e-23j, -1.55051985e-05+2.70074057e-17j],
        [-9.04150024e-17-4.21361589e-17j,  1.03815567e+00-6.58474262e-22j,
         -1.90808197e-05-2.26706786e-18j, -3.96212504e-01-2.70099741e-21j],
        [ 4.00419631e-01-3.18314602e-21j,  1.02663783e-04+3.85293150e-18j,
          1.03759996e+00+3.00108688e-23j,  5.56709872e-16-1.22756932e-16j],
        [ 5.48362500e-05-2.25357131e-18j, -1.94214253e-01+5.78817198e-22j,
         -2.90036787e-17+2.93774629e-18j,  1.03759996e+00-3.14151068e-23j]]),
 array([[ 1.03784583e+00+3.57328354e-21j,  2.37224937e-05-3.59529634e-17j,
         -1.93410936e-01-1.30701395e-21j,  2.45674201e-05-6.36247808e-17j],
        [-3.04712481e-05+4.58148494e-17j,  1.03735082e+00+3.37648668e-21j,
          2.47548008e-05-7.39296608e-18j,  3.96117366e-01+8.40812800e-21j],
        [-4.00514510e-01-9.76731859e-21j, -1.11793866e-04+3.29942684e-17j,
          1.03840

### decoupling matrix:

In [9]:
np.round(r.real, 7)

array([[ 1.0381557e+00,  0.0000000e+00,  1.9336510e-01, -1.5500000e-05],
       [-0.0000000e+00,  1.0381557e+00, -1.9100000e-05, -3.9621250e-01],
       [ 4.0041960e-01,  1.0270000e-04,  1.0376000e+00,  0.0000000e+00],
       [ 5.4800000e-05, -1.9421430e-01, -0.0000000e+00,  1.0376000e+00]])

# PART B: dynamic aperture

In [10]:
output_da_fn = 'output_da2.txt'

decoupled amplitudes to check:

In [11]:
u, v = 0.022, 0.022

can take ~10min:

In [12]:
run_fixfield_da(output_da_fn, b0f, b0d, m, xs, tilt_deg, x_clo, z_clo, r, u, v)

*** Running fixfield-da.exe...
*** Finished running fixfield.exe, output file written!


NB: make sure there's only 1 keyword to be read, as a setting in `proton3mev.beam` (otherwise the closed orbit is determined at each amplitude, taking away time)!

In [13]:
extract_da('output_da.txt')

((0.021, 0.021), True)

In [14]:
extract_da('output_da2.txt')

((0.022, 0.022), False)